name: Get task stats
on: [issue_comment]

jobs:
  get-stats:
      if: contains(github.event.comment.body, '/get-stats')
      runs-on: ubuntu-latest
      steps:
        - name: Get task stats
          uses: allegroai/trains-actions-get-stats@master
          id: train
          with:
            TRAINS_API_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
            TRAINS_API_SECRET_KEY: ${{ secrets.SECRET_KEY }}
            TRAINS_API_HOST: ${{ secrets.TRAINS_API_HOST }}
            TASK_ID: "6f98c7d181b84327ae12e64537a97960"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
